### PR TITLE
Feature/orca 306 Build API Gateway for internal_reconcile_report

### PR DESCRIPTION
**Pull request by rizbihassan**
## Summary of Changes

Addresses [ORCA-306: Build API Gateway for internal_reconcile_report](https://bugs.earthdata.nasa.gov/browse/ORCA-306)

## Changes

* updated api gateway main.tf and other relevant .tf files

## Type of change

- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update

## How Has This Been Tested?

deployed to aws and manually triggered the api to get the output without errors.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the necessary documentation (remove those that do not apply)
    - [ x] CHANGELOG.md
- [ x] My changes generate no new warnings
- [x ] New and existing unit tests pass locally with my changes
    - [x ] Automated tests passing (if not fork)
    - [x ] Manual testing/integration testing passes (if forked)
- [x ] My code has passed security scanning
    - [x ] Snyk
    - [x ] git-secrets

### CODE REVIEW

**Review by AndrewDorn — CHANGES_REQUESTED** [review]
Looks good. We do need to update api-gateway.md, though that isn't officially part of this task. That should either be done here so we can use your values from testing, or we should get a card on the backlog.

**Comment by rizbihassan** [comment]
> Looks good. We do need to update api-gateway.md, though that isn't officially part of this task. That should either be done here so we can use your values from testing, or we should get a card on the backlog.

Are you referring to https://github.com/nasa/cumulus-orca/blob/develop/website/docs/developer/research/research-APIGateway.md?

That is a research webpage which shows similar resources that I have here so I am not sure what else to add. The internal lambdas' README already shows the input and output you would expect from the api.

Though if I have a valid jobid, that could be used to test the output

**Comment by AndrewDorn** [comment]
> > Looks good. We do need to update api-gateway.md, though that isn't officially part of this task. That should either be done here so we can use your values from testing, or we should get a card on the backlog.
> 
> Are you referring to https://github.com/nasa/cumulus-orca/blob/develop/website/docs/developer/research/research-APIGateway.md?
> 
> That is a research webpage which shows similar resources that I have here so I am not sure what else to add. The internal lambdas' README already shows the input and output you would expect from the api.
> 
> Though if I have a valid jobid, that could be used to test the output



> > Looks good. We do need to update api-gateway.md, though that isn't officially part of this task. That should either be done here so we can use your values from testing, or we should get a card on the backlog.
> 
> Are you referring to https://github.com/nasa/cumulus-orca/blob/develop/website/docs/developer/research/research-APIGateway.md?
> 
> That is a research webpage which shows similar resources that I have here so I am not sure what else to add. The internal lambdas' README already shows the input and output you would expect from the api.
> 
> Though if I have a valid jobid, that could be used to test the output

**Comment by AndrewDorn** [comment]
> > Looks good. We do need to update api-gateway.md, though that isn't officially part of this task. That should either be done here so we can use your values from testing, or we should get a card on the backlog.
> 
> Are you referring to https://github.com/nasa/cumulus-orca/blob/develop/website/docs/developer/research/research-APIGateway.md?
> 
> That is a research webpage which shows similar resources that I have here so I am not sure what else to add. The internal lambdas' README already shows the input and output you would expect from the api.
> 
> Though if I have a valid jobid, that could be used to test the output

website/docs/developer/api/api-gateway.md

**Review by bhazuka — APPROVED** [review]
Looks ok to me. We should talk long term management of our API and documentation as we go forward so we do not have to update as many places.

**Review by AndrewDorn — APPROVED** [review]

**Pull request merged**
